# Generated by Django 5.1 on 2024-08-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_hunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='severity',
            field=models.CharField(max_length=50),
        ),
    ]
